"use client";
import React, { useState } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";

const Instructions = () => {
  const [currentInstruction, setCurrentInstruction] = useState(1);
  const route = useRouter();

  const instructions = {
    1: {
      text: "Make sure to complete the whole process to earn full credit!",
      image: "/in1.svg", // Add the correct path to your SVG file
    },
    2: {
      text: "This program uses AI to create customized content just for you!",
      image: "/in2.svg",
    },
    3: {
      text: "If a link isn't working, kindly check the main path for guidance.",
      image: "/in3.svg",
    },
    4: {
      text: "The content in this module is generated by AI.",
      image: "/in4.svg",
    },
  };

  const handlePrevious = () => {
    setCurrentInstruction(currentInstruction - 1);
  };

  const handleNext = () => {
    setCurrentInstruction(currentInstruction + 1);
  };

  const Submitted = () => {
    route.push("/params/page?page=DepartmentJobRolls");
  };

  return (
    <div className="flex justify-center items-center min-h-screen bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
      <div className="w-full max-w-lg shadow-lg rounded-lg overflow-hidden transform transition duration-500 hover:scale-105 bg-white dark:bg-gray-800">
        <div className="text-center text-3xl font-semibold bg-gradient-to-r from-purple-500 to-indigo-500 text-white p-6">
          Job Preparation
        </div>
        <div className="p-8">
          <div className="space-y-6">
            <div className="flex flex-col items-center space-y-4">
              <Image
                src={instructions[currentInstruction].image}
                alt={`Instruction ${currentInstruction} Image`}
                width={200}
                height={200}
                className="mb-4"
              />
            </div>

            <div className="p-6 rounded-md text-gray-800 dark:text-gray-200">
              <div className="flex flex-col items-center space-y-4">
                <p>{instructions[currentInstruction].text}</p>
              </div>
            </div>
            <div className="flex justify-between items-center mt-6">
              {currentInstruction > 1 && (
                <button
                  className="bg-gray-200 text-gray-700 hover:bg-gray-300 dark:bg-gray-700 dark:text-gray-200 dark:hover:bg-gray-600 px-4 py-2 rounded transition ease-in-out"
                  onClick={handlePrevious}
                >
                  Previous
                </button>
              )}
              {currentInstruction < 4 && (
                <button
                  className="bg-indigo-500 text-white hover:bg-indigo-600 dark:bg-indigo-600 dark:hover:bg-indigo-700 px-4 py-2 rounded transition ease-in-out"
                  onClick={handleNext}
                >
                  Next
                </button>
              )}
              {currentInstruction === 4 && (
                <button
                  className="bg-green-500 text-white hover:bg-green-600 dark:bg-green-600 dark:hover:bg-green-700 px-4 py-2 rounded transition ease-in-out"
                  onClick={Submitted}
                >
                  Get Started
                </button>
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Instructions;
